language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
before_script:
  - composer self-update
  - composer install
  - chmod -R 777 storage
script:
  - mkdir -p build/logs
  - chmod -R 777 build/logs
  - chmod -R 777 tests/resources
  - phpunit
after_script:
  - php vendor/bin/coveralls -v
